import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Provider from "@/components/Provider";
import QueryWrapper from "@/components/QueryWrapper";

export const metadata = {
  title: "Create SC2 Build Order App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <QueryWrapper>
          <Provider>
            <Navbar />

            <main>{children}</main>
            <Footer />
          </Provider>
        </QueryWrapper>
      </body>
    </html>
  );
}
